### ISSUE TITLE
Is the chart still working?

### ISSUE THREAD

**Issue by tandeman77** [google/auction-insights-visualization#1]
Hi, 

I added the chart to a new Google Data Studio dashboard today and followed the configuration steps.

Configuration:
Main Dimension (tried Day, Week, Month)
Breakdown Dimension: Auction Insights - Domain
Metric: Search Impr. Share

Result: 
The chart showed an error as in the image https://ibb.co/wzvzNxz

Would you be able to help? thank you!
Tan

**Comment by simonschellaert** [comment]
Hi Tan,

Sorry for the delayed reply on this! Make sure to select _Impr. Share_ as metric, as it doesn't work with _Search Impr. Share_. That should hopefully fix the issue!

Simon

**Comment by tandeman77** [comment]
worked like a charm. Thanks so much!
